all:
	@ cmake -S . -B ./build -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=C:/PSn00bSDK/lib/libpsn00b/cmake/sdk.cmake
	@ cmake --build ./build
	@ $(MAKE) -f Makefile.tools
	@ $(MAKE) -f Makefile.tim 
	@ $(MAKE) -f Makefile.cht 
	@ $(MAKE) -f Makefile.xa 
	@ mkpsxiso -y funkin.xml